name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Set your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # Set your Docker Hub password in GitHub Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: your-dockerhub-username/your-image-name:latest
